Fix `buf` when main has changed

diff --git a/.github/actions/check_style/action.yml b/.github/actions/check_style/action.yml
--- a/.github/actions/check_style/action.yml
+++ b/.github/actions/check_style/action.yml
@@ -2,26 +2,36 @@ name: "Check formatting"
 description: "Checks code formatting use cargo fmt"
 
 runs:
-    using: "composite"
-    steps:
-        - name: cargo fmt
-          shell: bash -euxo pipefail {0}
-          run: cargo fmt --all -- --check
+  using: "composite"
+  steps:
+    - name: cargo fmt
+      shell: bash -euxo pipefail {0}
+      run: cargo fmt --all -- --check
 
-        - name: cargo clippy
-          shell: bash -euxo pipefail {0}
-          # clippy.toml is not currently supporting specifying allowed lints
-          # so specify those here, and disable the rest until Zed's workspace
-          # will have more fixes & suppression for the standard lint set
-          run: |
-              cargo clippy --release --workspace --all-features --all-targets -- -A clippy::all -D clippy::dbg_macro -D clippy::todo
-              cargo clippy -p gpui
+    - name: cargo clippy
+      shell: bash -euxo pipefail {0}
+      # clippy.toml is not currently supporting specifying allowed lints
+      # so specify those here, and disable the rest until Zed's workspace
+      # will have more fixes & suppression for the standard lint set
+      run: |
+        cargo clippy --release --workspace --all-features --all-targets -- -A clippy::all -D clippy::dbg_macro -D clippy::todo
+        cargo clippy -p gpui
 
-        - name: Find modified migrations
-          shell: bash -euxo pipefail {0}
-          run: |
-              export SQUAWK_GITHUB_TOKEN=${{ github.token }}
-              . ./script/squawk
+      # when you push a new commit to a branch, it re-merges automatically
+      # BUT, if you click "run" manually (to approve a contributor request)
+      # then no re-merge is done, and so these actions that look at the diff
+      # to main give spurious failures
+    - name: re-merge
+      shell: bash -euxo pipefail {0}
+      run: |
+        git checkout -B temp
+        git merge -q -m "merge origin/main"
+
+    - name: Find modified migrations
+      shell: bash -euxo pipefail {0}
+      run: |
+        export SQUAWK_GITHUB_TOKEN=${{ github.token }}
+        . ./script/squawk
 
         - uses: bufbuild/buf-setup-action@v1
         - uses: bufbuild/buf-breaking-action@v1
